[2023-10-10T15:16:05.771+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_exam.transform_into_data.csv scheduled__2023-10-10T15:15:00+00:00 [queued]>
[2023-10-10T15:16:05.776+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_exam.transform_into_data.csv scheduled__2023-10-10T15:15:00+00:00 [queued]>
[2023-10-10T15:16:05.777+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T15:16:05.793+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_into_data.csv> on 2023-10-10 15:15:00+00:00
[2023-10-10T15:16:05.829+0000] {standard_task_runner.py:57} INFO - Started process 1631 to run task
[2023-10-10T15:16:05.836+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'transform_into_data.csv', 'scheduled__2023-10-10T15:15:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpx9wqrsxo']
[2023-10-10T15:16:05.840+0000] {standard_task_runner.py:85} INFO - Job 66: Subtask transform_into_data.csv
[2023-10-10T15:16:05.878+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-10T15:16:05.942+0000] {task_command.py:415} INFO - Running <TaskInstance: airflow_exam.transform_into_data.csv scheduled__2023-10-10T15:15:00+00:00 [running]> on host 137abce082a9
[2023-10-10T15:16:06.023+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_exam' AIRFLOW_CTX_TASK_ID='transform_into_data.csv' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T15:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-10T15:15:00+00:00'
[2023-10-10T15:16:06.026+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Transform.py", line 22, in transform_into_csv
    city_data = data_temp[city_name]
NameError: name 'city_name' is not defined
[2023-10-10T15:16:06.034+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=***_exam, task_id=transform_into_data.csv, execution_date=20231010T151500, start_date=20231010T151605, end_date=20231010T151606
[2023-10-10T15:16:06.041+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 66 for task transform_into_data.csv (name 'city_name' is not defined; 1631)
[2023-10-10T15:16:06.056+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T15:16:06.080+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
