[2023-10-10T15:19:04.956+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_exam.transform_into_data.csv scheduled__2023-10-10T15:18:00+00:00 [queued]>
[2023-10-10T15:19:04.962+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_exam.transform_into_data.csv scheduled__2023-10-10T15:18:00+00:00 [queued]>
[2023-10-10T15:19:04.962+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T15:19:04.971+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_into_data.csv> on 2023-10-10 15:18:00+00:00
[2023-10-10T15:19:04.981+0000] {standard_task_runner.py:57} INFO - Started process 1895 to run task
[2023-10-10T15:19:04.985+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'transform_into_data.csv', 'scheduled__2023-10-10T15:18:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmp_w771i4z']
[2023-10-10T15:19:04.986+0000] {standard_task_runner.py:85} INFO - Job 81: Subtask transform_into_data.csv
[2023-10-10T15:19:04.995+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-10T15:19:05.020+0000] {task_command.py:415} INFO - Running <TaskInstance: airflow_exam.transform_into_data.csv scheduled__2023-10-10T15:18:00+00:00 [running]> on host 137abce082a9
[2023-10-10T15:19:05.069+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_exam' AIRFLOW_CTX_TASK_ID='transform_into_data.csv' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T15:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-10T15:18:00+00:00'
[2023-10-10T15:19:05.073+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Transform.py", line 22, in transform_into_csv
    city_data = data_temp[city_name]
NameError: name 'city_name' is not defined
[2023-10-10T15:19:05.087+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=***_exam, task_id=transform_into_data.csv, execution_date=20231010T151800, start_date=20231010T151904, end_date=20231010T151905
[2023-10-10T15:19:05.097+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 81 for task transform_into_data.csv (name 'city_name' is not defined; 1895)
[2023-10-10T15:19:05.118+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T15:19:05.131+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
