[2023-10-10T19:56:05.994+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_exam.transform_into_data.csv scheduled__2023-10-10T19:55:00+00:00 [queued]>
[2023-10-10T19:56:06.034+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_exam.transform_into_data.csv scheduled__2023-10-10T19:55:00+00:00 [queued]>
[2023-10-10T19:56:06.038+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T19:56:06.101+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_into_data.csv> on 2023-10-10 19:55:00+00:00
[2023-10-10T19:56:06.125+0000] {standard_task_runner.py:57} INFO - Started process 1639 to run task
[2023-10-10T19:56:06.136+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'transform_into_data.csv', 'scheduled__2023-10-10T19:55:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpfcptbdfo']
[2023-10-10T19:56:06.138+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask transform_into_data.csv
[2023-10-10T19:56:06.153+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-10T19:56:06.220+0000] {task_command.py:415} INFO - Running <TaskInstance: airflow_exam.transform_into_data.csv scheduled__2023-10-10T19:55:00+00:00 [running]> on host 1d03f982e89a
[2023-10-10T19:56:06.366+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_exam' AIRFLOW_CTX_TASK_ID='transform_into_data.csv' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T19:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-10T19:55:00+00:00'
[2023-10-10T19:56:06.407+0000] {logging_mixin.py:151} INFO -     temperature        city  pression              date
0       301.51       Paris      1019  2023-10-10_16:24
1       295.22      London      1016  2023-10-10_16:24
2       282.73  Washington      1000  2023-10-10_16:24
3       301.51       Paris      1019  2023-10-10_16:23
4       295.22      London      1016  2023-10-10_16:23
5       282.62  Washington      1000  2023-10-10_16:23
6       301.51       Paris      1019  2023-10-10_16:22
7       295.22      London      1016  2023-10-10_16:22
8       282.73  Washington      1000  2023-10-10_16:22
9       301.51       Paris      1019  2023-10-10_16:21
[2023-10-10T19:56:06.416+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_transformation.py", line 35, in transform_into_csv
    df.to_csv(file, index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 259, in save
    self._save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 263, in _save
    self._save_header()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 268, in _save_header
    self.writer.writerow(self.encoded_labels)
io.UnsupportedOperation: not writable
[2023-10-10T19:56:06.443+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=***_exam, task_id=transform_into_data.csv, execution_date=20231010T195500, start_date=20231010T195605, end_date=20231010T195606
[2023-10-10T19:56:06.459+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task transform_into_data.csv (not writable; 1639)
[2023-10-10T19:56:06.508+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T19:56:06.535+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
