[2023-10-10T20:17:39.078+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_exam.transform_into_fulldata.csv scheduled__2023-10-10T20:16:00+00:00 [queued]>
[2023-10-10T20:17:39.085+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_exam.transform_into_fulldata.csv scheduled__2023-10-10T20:16:00+00:00 [queued]>
[2023-10-10T20:17:39.085+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T20:17:39.097+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_into_fulldata.csv> on 2023-10-10 20:16:00+00:00
[2023-10-10T20:17:39.130+0000] {standard_task_runner.py:57} INFO - Started process 933 to run task
[2023-10-10T20:17:39.136+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'transform_into_fulldata.csv', 'scheduled__2023-10-10T20:16:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpsoz6ysfn']
[2023-10-10T20:17:39.138+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask transform_into_fulldata.csv
[2023-10-10T20:17:39.153+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-10T20:17:39.202+0000] {task_command.py:415} INFO - Running <TaskInstance: airflow_exam.transform_into_fulldata.csv scheduled__2023-10-10T20:16:00+00:00 [running]> on host 11df5857e4c6
[2023-10-10T20:17:39.245+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_exam' AIRFLOW_CTX_TASK_ID='transform_into_fulldata.csv' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T20:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-10T20:16:00+00:00'
[2023-10-10T20:17:39.260+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_transformation.py", line 17, in transform_into_csv
    data_temp = json.load(file)
  File "/usr/local/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-10-10T20:17:39.267+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=***_exam, task_id=transform_into_fulldata.csv, execution_date=20231010T201600, start_date=20231010T201739, end_date=20231010T201739
[2023-10-10T20:17:39.273+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task transform_into_fulldata.csv (Expecting value: line 1 column 1 (char 0); 933)
[2023-10-10T20:17:39.309+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T20:17:39.326+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
