[2023-10-10T15:25:46.252+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_exam.transform_into_data.csv manual__2023-10-10T15:25:38.357980+00:00 [queued]>
[2023-10-10T15:25:46.268+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_exam.transform_into_data.csv manual__2023-10-10T15:25:38.357980+00:00 [queued]>
[2023-10-10T15:25:46.270+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T15:25:46.282+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_into_data.csv> on 2023-10-10 15:25:38.357980+00:00
[2023-10-10T15:25:46.298+0000] {standard_task_runner.py:57} INFO - Started process 2495 to run task
[2023-10-10T15:25:46.303+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'transform_into_data.csv', 'manual__2023-10-10T15:25:38.357980+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmplkb1qgit']
[2023-10-10T15:25:46.306+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask transform_into_data.csv
[2023-10-10T15:25:46.333+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-10T15:25:46.375+0000] {task_command.py:415} INFO - Running <TaskInstance: airflow_exam.transform_into_data.csv manual__2023-10-10T15:25:38.357980+00:00 [running]> on host 137abce082a9
[2023-10-10T15:25:46.425+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_exam' AIRFLOW_CTX_TASK_ID='transform_into_data.csv' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T15:25:38.357980+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-10T15:25:38.357980+00:00'
[2023-10-10T15:25:46.427+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Transform.py", line 24, in transform_into_csv
    'temperature': data_city['main']['temp'],
TypeError: string indices must be integers
[2023-10-10T15:25:46.435+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=***_exam, task_id=transform_into_data.csv, execution_date=20231010T152538, start_date=20231010T152546, end_date=20231010T152546
[2023-10-10T15:25:46.444+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 115 for task transform_into_data.csv (string indices must be integers; 2495)
[2023-10-10T15:25:46.484+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T15:25:46.517+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
