[2023-10-10T15:34:13.574+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_exam.train_best_model scheduled__2023-10-10T15:33:00+00:00 [queued]>
[2023-10-10T15:34:13.578+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_exam.train_best_model scheduled__2023-10-10T15:33:00+00:00 [queued]>
[2023-10-10T15:34:13.579+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T15:34:13.586+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): train_best_model> on 2023-10-10 15:33:00+00:00
[2023-10-10T15:34:13.599+0000] {standard_task_runner.py:57} INFO - Started process 3441 to run task
[2023-10-10T15:34:13.602+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'train_best_model', 'scheduled__2023-10-10T15:33:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpgru5_d_y']
[2023-10-10T15:34:13.603+0000] {standard_task_runner.py:85} INFO - Job 176: Subtask train_best_model
[2023-10-10T15:34:13.620+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-10T15:34:13.659+0000] {task_command.py:415} INFO - Running <TaskInstance: airflow_exam.train_best_model scheduled__2023-10-10T15:33:00+00:00 [running]> on host 137abce082a9
[2023-10-10T15:34:13.740+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_exam' AIRFLOW_CTX_TASK_ID='train_best_model' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T15:33:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-10T15:33:00+00:00'
[2023-10-10T15:34:13.829+0000] {logging_mixin.py:151} INFO - LinearRegression() saved at  app/clean_data/best_model.pickle
[2023-10-10T15:34:13.830+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Load_ml.py", line 109, in save_best_model
    train_and_save_model(
  File "/opt/airflow/dags/Load_ml.py", line 27, in train_and_save_model
    dump(model, path_to_model)
  File "/home/airflow/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 552, in dump
    with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'app/clean_data/best_model.pickle'
[2023-10-10T15:34:13.838+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=***_exam, task_id=train_best_model, execution_date=20231010T153300, start_date=20231010T153413, end_date=20231010T153413
[2023-10-10T15:34:13.850+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 176 for task train_best_model ([Errno 2] No such file or directory: 'app/clean_data/best_model.pickle'; 3441)
[2023-10-10T15:34:13.896+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T15:34:13.931+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
