[2023-10-10T15:17:06.814+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_exam.transform_into_fulldata.csv scheduled__2023-10-10T15:16:00+00:00 [queued]>
[2023-10-10T15:17:06.823+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_exam.transform_into_fulldata.csv scheduled__2023-10-10T15:16:00+00:00 [queued]>
[2023-10-10T15:17:06.823+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T15:17:06.836+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_into_fulldata.csv> on 2023-10-10 15:16:00+00:00
[2023-10-10T15:17:06.856+0000] {standard_task_runner.py:57} INFO - Started process 1700 to run task
[2023-10-10T15:17:06.882+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'transform_into_fulldata.csv', 'scheduled__2023-10-10T15:16:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpldjwbeuk']
[2023-10-10T15:17:06.886+0000] {standard_task_runner.py:85} INFO - Job 70: Subtask transform_into_fulldata.csv
[2023-10-10T15:17:06.926+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-10T15:17:07.031+0000] {task_command.py:415} INFO - Running <TaskInstance: airflow_exam.transform_into_fulldata.csv scheduled__2023-10-10T15:16:00+00:00 [running]> on host 137abce082a9
[2023-10-10T15:17:07.107+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_exam' AIRFLOW_CTX_TASK_ID='transform_into_fulldata.csv' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T15:16:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-10T15:16:00+00:00'
[2023-10-10T15:17:07.108+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Transform.py", line 22, in transform_into_csv
    city_data = data_temp[city_name]
NameError: name 'city_name' is not defined
[2023-10-10T15:17:07.114+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=***_exam, task_id=transform_into_fulldata.csv, execution_date=20231010T151600, start_date=20231010T151706, end_date=20231010T151707
[2023-10-10T15:17:07.120+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 70 for task transform_into_fulldata.csv (name 'city_name' is not defined; 1700)
[2023-10-10T15:17:07.159+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T15:17:07.199+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
