[2023-10-10T15:20:06.656+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: airflow_exam.transform_into_fulldata.csv scheduled__2023-10-10T15:19:00+00:00 [queued]>
[2023-10-10T15:20:06.662+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: airflow_exam.transform_into_fulldata.csv scheduled__2023-10-10T15:19:00+00:00 [queued]>
[2023-10-10T15:20:06.662+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-10T15:20:06.670+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_into_fulldata.csv> on 2023-10-10 15:19:00+00:00
[2023-10-10T15:20:06.702+0000] {standard_task_runner.py:57} INFO - Started process 2023 to run task
[2023-10-10T15:20:06.706+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', '***_exam', 'transform_into_fulldata.csv', 'scheduled__2023-10-10T15:19:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/DAG.py', '--cfg-path', '/tmp/tmpf0fs3b5j']
[2023-10-10T15:20:06.707+0000] {standard_task_runner.py:85} INFO - Job 91: Subtask transform_into_fulldata.csv
[2023-10-10T15:20:06.722+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-10-10T15:20:06.768+0000] {task_command.py:415} INFO - Running <TaskInstance: airflow_exam.transform_into_fulldata.csv scheduled__2023-10-10T15:19:00+00:00 [running]> on host 137abce082a9
[2023-10-10T15:20:06.839+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='***_exam' AIRFLOW_CTX_TASK_ID='transform_into_fulldata.csv' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T15:19:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-10T15:19:00+00:00'
[2023-10-10T15:20:06.842+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Transform.py", line 22, in transform_into_csv
    city_data = data_temp[city_name]
NameError: name 'city_name' is not defined
[2023-10-10T15:20:06.853+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=***_exam, task_id=transform_into_fulldata.csv, execution_date=20231010T151900, start_date=20231010T152006, end_date=20231010T152006
[2023-10-10T15:20:06.863+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 91 for task transform_into_fulldata.csv (name 'city_name' is not defined; 2023)
[2023-10-10T15:20:06.883+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-10T15:20:06.906+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
